// <auto-generated />
namespace DLL_DBWorker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreatetablesMapsandTextures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreatetablesMapsandTextures));
        
        string IMigrationMetadata.Id
        {
            get { return "201711222152002_Create tables Maps and Textures"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
